### ISSUE TITLE
Step 1 ran for only one block and one chromosome

### ISSUE THREAD

**Issue by adrianICG** [rgcgithub/regenie#37] opened 2020-09-23 08:36 UTC
Really enjoying Regenie and its speed. I've stumbled upon a behaviour which I'm not sure if its a bug. I am running a GWAS on the UK-Biobank, but step 1 finished very quickly (Elapsed time : 325.766s). Upon inspection the output had only processed 1 block from chromosome one. Is this a normal behaviours? Should it not process several blocks and go through all the chromosomes in the input bfile? 

Below the first part of the log file:

              Start time: Wed Sep 23 16:34:53 2020

              |==================================|
              |           REGENIE v1.0.5.4       |
              |==================================|

              Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
              Distributed under the MIT License.

              Log of output saved in file : ukb_step1.log

              Options in effect:
                --step 1 \
                --bed /PATH/regenie/boltlmm_GRM_201803_allchr1_22_maf05 \
                --phenoFile Phenos.tsv \
                --phenoColList PP1,PP2,PP3,PP4,PP5,PP6,PP7,PP8,PP9 \
                --covarFile Covars.tsv \
                --covarColList Sex,Age,array,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
                --bt \
                --bsize 2000 \
                --threads 8 \
                --out ukb_step1_pain
              
              Fitting null model
               * bim              : [/PATH/boltlmm_GRM_201803_allchr1_22_maf05.bim] n_snps = 163061
               * fam              : [/PATH/regenie/boltlmm_GRM_201803_allchr1_22_maf05.fam] n_samples = 487406
               * bed              : [/PATH/regenie/boltlmm_GRM_201803_allchr1_22_maf05.bed]
               * phenotypes       : [Phenos.tsv] n_pheno = 9
                 -number of phenotyped individuals = 436088
               * covariates       : [Covars.tsv] n_cov = 13
                 -number of individuals with covariate data = 438648
               * number of individuals used in analysis = 436088
                 -fitting null logistic regression on binary phenotypes...done (4581ms)
                 -residualizing and scaling phenotypes...done (88ms)
               * # threads        : [8]
               * block size       : [2000]
               * # blocks         : [1]
               * # CV folds       : [5]
               * ridge data_l0    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
               * ridge data_l1    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
               * approximate memory usage : 8GB
               * setting memory...done
              
              Chromosome 1
               block [1] : 2000 snps  (57770ms)
                 -residualizing and scaling genotypes...done (33074ms)
                 -calc working matrices...done (90955ms)
                 -calc level 0 ridge...done (81565ms)
              
               Level 1 ridge with logistic regression...
                 -on phenotype 1 (PP1)...done (1435ms)
                 -on phenotype 2 (PP2)...done (1575ms)
                 -on phenotype 3 (PP3)...done (1651ms)
                 -on phenotype 4 (PP4)...done (1603ms)
                 -on phenotype 5 (PP5)...done (1597ms)
                 -on phenotype 6 (PP6)...done (1662ms)
                 -on phenotype 7 (PP7)...done (1668ms)
                 -on phenotype 8 (PP8)...done (1597ms)
                 -on phenotype 9 (PP9)...done (1551ms)

Thanks a lot!

**Comment by joellembatchou** [comment] 2020-09-23 13:50
Hi,

You can update to the most recent version of the software (this bug was fixed in version >=1.0.5.5).

Cheers,
Joelle

**Comment by adrianICG** [comment] 2020-09-29 03:47
Thanks Joelle,

I have compiled v1.0.6.2 now, but the provided example fails after the level 1 ridge is done:

	Running step 1 of REGENIE
	==================================
	Start time: Tue Sep 29 13:43:02 2020
	
	              |==============================|
	              |        REGENIE v1.0.6.2      |
	              |==============================|
	
	Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
	Distributed under the MIT License.
	
	Log of output saved in file : test/fit_bin_out.log
	
	Options in effect:
	  --step 1 \
	  --bed example/example \
	  --exclude example/snplist_rm.txt \
	  --covarFile example/covariates.txt \
	  --phenoFile example/phenotype_bin.txt \
	  --remove example/fid_iid_to_remove.txt \
	  --bsize 100 \
	  --bt \
	  --lowmem \
	  --lowmem-prefix tmp_rg \
	  --out test/fit_bin_out
	
	Fitting null model
	 * bim              : [example/example.bim] n_snps = 1000
	   -removing variants specified in [example/snplist_rm.txt]
	     +number of variants remaining in the analysis = 994
	 * fam              : [example/example.fam] n_samples = 500
	   -removing individuals specified in [example/fid_iid_to_remove.txt]
	     +number of genotyped individuals to exclude from the analysis = 6
	 * bed              : [example/example.bed]
	 * phenotypes       : [example/phenotype_bin.txt] n_pheno = 2
	   -number of phenotyped individuals = 494
	 * covariates       : [example/covariates.txt] n_cov = 3
	   -number of individuals with covariate data = 494
	 * number of individuals used in analysis = 494
	   -fitting null logistic regression on binary phenotypes...done (0ms)
	   -residualizing and scaling phenotypes...done (0ms)
	   -WARNING: Sample size is less than 5,000 so using LOOCV instead of 5-fold CV.
	 * # threads        : [64]
	 * block size       : [100]
	 * # blocks         : [10]
	 * # CV folds       : [494]
	 * ridge data_l0    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
	 * ridge data_l1    : [5 : 0.01 0.25 0.5 0.75 0.99 ]
	 * approximate memory usage : 955MB
	 * writing level 0 predictions to disk
	   -temporary files will have prefix [tmp_rg_l0_Y]
	   -approximate disk space needed : 1MB
	 * setting memory...done
	
	Chromosome 1
	 block [1] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (51ms)
	   -calc level 0 ridge...done (80ms)
	 block [2] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (70ms)
	   -calc level 0 ridge...done (78ms)
	 block [3] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (64ms)
	   -calc level 0 ridge...done (91ms)
	 block [4] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (57ms)
	   -calc level 0 ridge...done (63ms)
	 block [5] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (2ms)
	   -calc working matrices...done (60ms)
	   -calc level 0 ridge...done (85ms)
	 block [6] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (57ms)
	   -calc level 0 ridge...done (88ms)
	 block [7] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (59ms)
	   -calc level 0 ridge...done (80ms)
	 block [8] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (53ms)
	   -calc level 0 ridge...done (75ms)
	 block [9] : 100 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (52ms)
	   -calc level 0 ridge...done (73ms)
	 block [10] : 94 snps  (0ms)
	   -residualizing and scaling genotypes...done (0ms)
	   -calc working matrices...done (63ms)
	   -calc level 0 ridge...done (75ms)
	
	 Level 1 ridge with logistic regression...
	   -on phenotype 1 (Y1)...done (22ms)
	   -on phenotype 2 (Y2)...done (14ms)
	
	Output
	------
	terminate called after throwing an instance of 'std::bad_alloc'
	  what():  std::bad_alloc
	phenotype 1 (Y1) : ./test_bash.sh: line 63: 224259 Aborted                 (core dumped) ./$regenie_bin $rgcmd
	Step 1 of REGENIE did not finish successfully. Update to most recent REGENIE version (using 'git pull') and re-compile the software (using 'make clean && make').
	

Thank you for all your help!
Adrian

**Comment by joellembatchou** [comment] 2020-09-29 17:11
Could you try with the provided pre-compiled binary in https://github.com/rgcgithub/regenie/releases/tag/v1.0.6.2 ?

I just tried it and the test script ran fine (working directory is the Regenie clone gut hub repo)
```
wget https://github.com/rgcgithub/regenie/releases/download/v1.0.6.2/regenie_v1.0.6.2.gz_x86_64_Linux -O regenie
chmod u+x regenie
./test/test_bash.sh --path .
```

**Comment by adrianICG** [comment] 2020-09-30 00:40
Upon trying that I get the error:

    ./regenie_v1.0.6.2.gz_x86_64_Linux: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory

Is the system missing some dependency?

**Comment by joellembatchou** [comment] 2020-09-30 02:26
The binary was compiled with GLIBC version 2.23. It seems the version installed on your machine is <2.22 (if on Ubuntu, you could check your version using `ldd --version`). Which OS are you using? (we do the testing on Ubuntu & Mac OSX environments)

Alternatively, there are docker images available in https://github.com/rgcgithub?tab=packages. that you could use (there is also a Dockerfile in the main directory [you could use `make docker-build` if you have docker installed]).

**Comment by CanWood** [comment] 2020-09-30 05:07
Hi, Joelle,

We (adrianIGC) and I are on a CentOS 7 system which has glibc 2.17 which is why the prebuilt is giving us the error Adrian mentioned above.  I've cloned the repo, checked out v1.0.6.2 and we're still getting the same error:

`
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
phenotype 1 (Y1) : ./test_bash.sh: line 63: 59927 Aborted                 (core dumped) ./$regenie_bin $rgcmd
Step 1 of REGENIE did not finish successfully. Update to most recent REGENIE version (using 'git pull') and re-compile the software (using 'make clean && make').`

Any troubleshooting tips?

Cheers!

**Comment by CanWood** [comment] 2020-10-09 05:59
Hi All,

I recompiled this with gcc-7.5.0 and we now have a working binary.  I'll leave it to adrianIGC to comment on whether this binary has addressed his original concern.

Cheers!

**Closed** 2020-10-12 00:46 UTC

**Comment by Shicheng-Guo** [comment] 2021-04-05 03:58
I received `74458 Bus error (core dumped)` in step 1.  You can find the job is failed in block 335 (whole number is 537 blocks) Not sure it is caused by regenie or our HPC. 

```
 block [334] : 1000 snps  (18522ms)
   -residualizing and scaling genotypes...done (8388ms)
   -calc working matrices...done (20073ms)
   -calc level 0 ridge...done (17847ms)
 **block [335]** : 1000 snps  (18991ms)
   -residualizing and scaling genotypes.../cm/local/apps/slurm/var/spool/job1900115/slurm_script: line 25: 74458 Bus error               (core dumped) regenie --step 1 --bed ukb_cal_allChrs --extract qc_pass.snplist --keep qc_pass.id -->
(END)
```
Here is the job: 

```
#!/bin/bash
#SBATCH --account=jan100
#SBATCH -p compute
#SBATCH --mem=248G
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=sguo2@its.jnj.com
#SBATCH --time 48:00:00
#SBATCH --nodes 1
#SBATCH --ntasks-per-node=16
cd /home/sguo2/janssen4/ukb/Genotyped-hg19/plink
regenie \
  --step 1 \
  --bed ukb_cal_allChrs \
  --extract qc_pass.snplist \
  --keep qc_pass.id \
  --phenoFile /home/sguo2/janssen4/ukb/WES-hg38/WES.chrX.sigTest.pheno.txt\
  --covarFile /home/sguo2/janssen4/ukb/WES-hg38/UKB.cov.r2.Guo.txt \
  --phenoColList X218,X272 \
  --covarCol PC{1:20} --covarCol Year \
  --threads 16 \
  --covarCol YearSquare --covarCol center \
  --bt \
  --bsize 1000 \
  --out ukb_m_step1 \
```

```
(base) [sguo2@login02 plink]$ regenie
              |============================|
              |        REGENIE v2.0.2      |
              |============================|

Copyright (c) 2020 Joelle Mbatchou and Jonathan Marchini.
Distributed under the MIT License.

ERROR: You must provide an output prefix using '--out'
For more information, use option '--help' or visit the website: https://rgcgithub.github.io/regenie/

(base) [sguo2@login02 plink]$
````

**Comment by joellembatchou** [comment] 2021-04-05 16:47
Hi,

It does not seem to be a memory issue as it looks like you are only analyzing 2 traits and the system has 248GB allocated. I'd suggest re-running this on your local machine and seeing if it fails and if so, does it fail at the same block number (i.e. 335). 

Cheers,
Joelle
