### ISSUE TITLE
Core dump in step 1 in the regenie v3.2.7

### ISSUE THREAD

**Issue by Apprentice2** [rgcgithub/regenie#419] opened 2023-06-08 01:57 UTC
I have performed the step 1 analysis using regenie v3.2.5 and v3.2.7 respectively with the same command. Then, the analysis was completed successfully with v3.2.5, but with v3.2.7, it terminates abnormally with the following error message. Why is this? I would be grateful if you could enlighten me.

The commands are as follows

regenie_v3.2.7.gz_x86_64_Linux \
  --step 1 \
  --bed data_bed \
  --phenoFile data.tsv \
  --phenoColList pheno \
  --covarFile data.tsv \
  --covarColList age,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,PCA_10 \
  --catCovarList sex,group \
  --bsize 1000 \
  --qt \
  --lowmem \
  --lowmem-prefix regenie_temp_predictors_1 \
  --threads 96 \
  --maxCatLevels 99 \
  --gz \
  --out pheno_step1

The error message is as follows

---------------------------------------------------
Output
------
phenotype 1 (pheno) : 
  0.01  : Rsq = 0.0496473, MSE = 0.97723
  0.25  : Rsq = 0.0582045, MSE = 0.943553<- min value
  0.5   : Rsq = 0.0623716, MSE = 0.946552
  0.75  : Rsq = 0.0650504, MSE = 0.952831
  0.99  : Rsq = 0.0786564, MSE = 0.961713
  * making predictions...regenie_v3.2.7.gz_x86_64_Linux: /home/s.joelle.mbatchou/software/regenie/external_libs/eigen-3.4.0/Eigen/src/Core/DenseCoeffsBase.h:427: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Array<int, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = int; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
./1_step1.bsh: 22 行: 132749 Aborted                 (coredump) regenie_v3.2.7.gz_x86_64_Linux --step 1 --bed data_bed --phenoFile data.tsv --phenoColList pheno --covarFile data.tsv --covarColList age,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,PCA_10 --catCovarList sex,group --bsize 1000 --qt --lowmem --lowmem-prefix regenie_temp_predictors_1 --threads 96 --maxCatLevels 99 --gz --out pheno_step1
---------------------------------------------------

The OS of my PC is Ubuntu 22 LTS.

**Comment by joellembatchou** [comment] 2023-06-08 13:21
Duplicate of #413

**Closed** 2023-10-12 16:45 UTC
Labels: bug, duplicate
